// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ6FGLOBR62xZE6XNpIcvX6XU0_IspQaA',
    appId: '1:957413115353:web:c11bcf99ea26981af0c5c8',
    messagingSenderId: '957413115353',
    projectId: 'social-media-cc3ac',
    authDomain: 'social-media-cc3ac.firebaseapp.com',
    storageBucket: 'social-media-cc3ac.appspot.com',
    measurementId: 'G-2JBEFJT5JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtsUpk5YdX_Mx2lOLDg07_rctLDGBOqIg',
    appId: '1:957413115353:android:70842488054e9394f0c5c8',
    messagingSenderId: '957413115353',
    projectId: 'social-media-cc3ac',
    storageBucket: 'social-media-cc3ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8cBQ9qqNssdMgQTLkd-Q0YA0YQ5mhog',
    appId: '1:957413115353:ios:f827f53d545d6cbbf0c5c8',
    messagingSenderId: '957413115353',
    projectId: 'social-media-cc3ac',
    storageBucket: 'social-media-cc3ac.appspot.com',
    iosClientId: '957413115353-12fale9878qorrhvkeg95j39etfjts71.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP8cBQ9qqNssdMgQTLkd-Q0YA0YQ5mhog',
    appId: '1:957413115353:ios:f827f53d545d6cbbf0c5c8',
    messagingSenderId: '957413115353',
    projectId: 'social-media-cc3ac',
    storageBucket: 'social-media-cc3ac.appspot.com',
    iosClientId: '957413115353-12fale9878qorrhvkeg95j39etfjts71.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
